language: python
python:
  - 2.7
sudo: false

# Setup anaconda
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

# Install packages
install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython ipython ipyparallel pyzmq tornado networkx mpi4py
  - pip install nose-cov python-coveralls
  - pip install git+https://github.com/simpeg/simpeg.git@parallel
  # - pip install -r requirements.txt
  - python setup.py install
  - ./zephyr/Tests/setup_parallel_environment.sh

# Run test
script:
  - ipcluster start -n4 --profile mpi --daemon
  - sleep 10
  - nosetests --with-cov --cov zephyr --cov-config .coveragerc -v -s
  - ipcluster stop --profile mpi || true

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

notifications:
  email:
    - brendan@bitsmithy.net
